[tox]
envlist = ty, py3.{11,12,13,14}

[testenv]
package = wheel
wheel_build_env = .pkg
deps=
    pytest
    pytest-raises
commands =
    pytest

[testenv:install]
skip_install = True
deps=
    build
    twine
commands=
    pip check {toxinidir}
    python -m build {toxinidir}
    twine check {toxinidir}/dist/*

[testenv:ty]
passenv =
    TY_OUTPUT_FORMAT
deps=
    ty
    pytest
commands=
    ty check

[pytest]
testpaths =
    tests
markers =
    raises
