"""Ontologies: terms, lookup and generation.

The ontologies are shipped as classes generated from the ontology releases, so a
term is completed by the editor, checked at runtime and carries what the
ontology says about it instead of being an opaque string.

| ontology | terms |
| --- | --- |
| `SBO` | Systems Biology Ontology, roles of model components |
| `KISAO` | Kinetic Simulation Algorithm Ontology, simulation algorithms |
| `PBPKO` | PBPK Ontology, physiologically based pharmacokinetic modeling |

Every term is available under its identifier and under its name, and `validate`
accepts both the underscore and the colon notation:

```python
from pymetadata.ontologies import SBO

SBO.SBO_0000247                    # by id
SBO.SIMPLE_CHEMICAL                # by name
SBO.validate("SBO:0000247")        # SBO.SBO_0000247
SBO.get_name(SBO.SIMPLE_CHEMICAL)  # 'simple chemical'
```

A term is a `str`, i.e., the identifier, with the information of the ontology
release on it, see `OntologyTerm`:

```python
SBO.SIMPLE_CHEMICAL == "SBO_0000247"  # True
SBO.SIMPLE_CHEMICAL.label             # 'simple chemical'
SBO.SIMPLE_CHEMICAL.definition        # 'Simple, non-repetitive chemical entity.'
SBO.SIMPLE_CHEMICAL.curie             # 'SBO:0000247'
```

The `<ONTOLOGY>Type` aliases are `str | <ONTOLOGY>` and are the type to accept
in a signature which takes either a term or the identifier as a string.

The generated modules are large, so they are imported on first access instead of
with the package: looking up a term in OLS (`pymetadata.webservices.ols`) does
not pay for them. They are generated by the internal `_ontology_builder` module
and should never be edited by hand.
"""

import importlib
from typing import TYPE_CHECKING, Any

from pymetadata.ontologies.term import OntologyMeta, OntologyTerm, TermData

if TYPE_CHECKING:
    from .kisao import KISAO, KISAOType
    from .pbpko import PBPKO, PBPKOType
    from .sbo import SBO, SBOType

__all__ = [
    "KISAO",
    "PBPKO",
    "SBO",
    "KISAOType",
    "OntologyMeta",
    "OntologyTerm",
    "PBPKOType",
    "SBOType",
    "TermData",
]

#: module of the generated ontologies, keyed by the name they are exported under
_TERM_MODULES: dict[str, str] = {
    "KISAO": "kisao",
    "KISAOType": "kisao",
    "PBPKO": "pbpko",
    "PBPKOType": "pbpko",
    "SBO": "sbo",
    "SBOType": "sbo",
}


def __getattr__(name: str) -> Any:
    """Import a generated ontology module on first access.

    Args:
        name: name of an ontology or of one of the type aliases

    Returns:
        The ontology or type alias.

    Raises:
        AttributeError: if the package has no such attribute
    """
    module_name = _TERM_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

    attribute = getattr(importlib.import_module(f".{module_name}", __name__), name)
    # cache the attribute, the next access does not enter `__getattr__` again
    globals()[name] = attribute
    return attribute


def __dir__() -> list[str]:
    """List the attributes of the package, including ontologies not yet imported.

    Returns:
        The attribute names.
    """
    return sorted(set(globals()) | set(__all__))
